source 'http://rubygems.corp.yahoo.co.jp:8000/apj-rubygems'

gem 'bundler_cache'
gem 'npm_cache'

gem 'danger'
gem 'danger-lgtm'
gem 'danger-todoist'
gem 'danger-changelog'
gem 'rubocop'
gem 'danger-rubocop'
gem 'danger-commit_lint'
gem 'danger-ios_logs'
gem 'danger-textlint'
gem 'danger-checkstyle_format'
gem 'danger-junit'
gem 'danger-android_lint'
gem 'danger-jacoco'
