######################################################################
## Load Plugins
######################################################################

branch ||= ENV['HOSTED_DANGER_SHARED_BRANCH'] # env for development
branch ||= github.pr_json.head.repo.full_name == "yahoojapan/hosted-danger" ? github.branch_for_head : "master"

danger.import_plugin("https://raw.githubusercontent.com/yahoojapan/hosted-danger/master/plugins/test_report.rb")
danger.import_plugin("https://raw.githubusercontent.com/yahoojapan/hosted-danger/master/plugins/code_coverage.rb")
danger.import_plugin("https://raw.githubusercontent.com/yahoojapan/hosted-danger/master/plugins/test_code.rb")
danger.import_plugin("https://raw.githubusercontent.com/yahoojapan/hosted-danger/master/plugins/review.rb")
danger.import_plugin("https://raw.githubusercontent.com/yahoojapan/hosted-danger/master/plugins/common_rule.rb")
danger.import_plugin("https://raw.githubusercontent.com/yahoojapan/hosted-danger/master/plugins/slack.rb")
