#!/usr/bin/env bash

echo "Start pushing onto "\"$1\"

git config --global user.email "screwdriver-admin@ml.yahoo-corp.jp"
git config --global user.name "ap-screwdriver"

git reset --hard origin/$1
rm -f update && echo `date` > update

git add update
git commit -m "[skip ci] `date`"
git push origin $1:HEAD
