#!/bin/sh

crystal tool format --check &> /dev/null
ret_code=$?

if [ 0 -ne $ret_code ]; then
  crystal tool format
  echo "Files formatted. Please review results and commit ;)"
  exit $ret_code
else
  exit 0
fi