#!/usr/bin/env ruby

require "json"

if ARGV.size < 3
  help_message = <<-HELP

ap-dangerのリポジトリの登録数を取得するスクリプトです

```
$ tools/repo_counting [ghe.corpのaccess token] [git.corpのaccess token] [partner.git.corpのaccess token]
```
HELP

  puts help_message
  exit 0
end

def header(host)
  case host
  when "ghe.corp.yahoo.co.jp"
    "-H \"Authorization: token #{ARGV[0]}\""
  when "git.corp.yahoo.co.jp"
    "-H \"Authorization: token #{ARGV[1]}\""
  when "partner.git.corp.yahoo.co.jp"
    "-H \"Authorization: token #{ARGV[2]}\""
  end
end

def repos(host)
  repos_urls = JSON.parse(`curl #{header(host)} --silent https://#{host}/api/v3/user/orgs`).map { |j| j["repos_url"].to_s }

  jsons = []
  jsons << JSON.parse(`curl #{header(host)} --silent https://#{host}/api/v3/users/ap-danger/repos?type=all`)
  jsons << JSON.parse(`curl #{header(host)} --silent https://#{host}/api/v3/user/repos`)

  repos_urls.each do |repos_url|
    jsons << JSON.parse(`curl #{header(host)} --silent #{repos_url}`)
  end

  jsons.map { |json| json.map { |j| j["html_url"].to_s } }.flatten.uniq.reject { |repo| member_repo?(repo) }
end

def member_repo?(repo)
  members = ["tahori", "kasonoda", "taicsuzu", "atyamash", "gelee", "ap-approduce", "ap-danger", "approduce", "hosted-danger"]
  members.each do |member|
    return true if repo.include?(member)
  end

  false
end

ghe = repos("ghe.corp.yahoo.co.jp")
git = repos("git.corp.yahoo.co.jp")
partner = repos("partner.git.corp.yahoo.co.jp")

msg = <<-MSG
Hosted Danger利用リポジトリを集計します (メンバーのリポジトリは含まれません)

------- ghe -------
リポジトリ数: #{ghe.size}

#{ghe.join("\n")}

------- git -------
リポジトリ数: #{git.size}

#{git.join("\n")}

------- partner -------
リポジトリ数: #{partner.size}

#{partner.join("\n")}

-------------------
合計: #{ghe.size + git.size + partner.size}

MSG

puts msg
