#!/usr/bin/env bash

rm -rf envs.json

if [[ -z "${ACCESS_TOKEN_GHE}" ]]; then
    echo "Please set \$ACCESS_TOKEN_GHE for the building"
    exit -1
fi

if [[ -z "${ACCESS_TOKEN_PARTNER}" ]]; then
    echo "Please set \$ACCESS_TOKEN_PARTNER for the building"
    exit -1
fi

if [[ -z "${ACCESS_TOKEN_GIT}" ]]; then
    echo "Please set \$ACCESS_TOKEN_GIT for the building"
    exit -1
fi

if [[ -z "${DRAGON_ACCESS_KEY}" ]]; then
    echo "Please set \$DRAGON_ACCESS_KEY for the building"
    exit -1
fi

if [[ -z "${DRAGON_SECRET_ACCESS_KEY}" ]]; then
    echo "Please set \$DRAGON_SECRET_ACCESS_KEY for the building"
    exit -1
fi

echo "{\"access_token_ghe\": \"$ACCESS_TOKEN_GHE\", \"access_token_partner\": \"$ACCESS_TOKEN_PARTNER\", \"access_token_git\": \"$ACCESS_TOKEN_GIT\", \"dragon_access_key\": \"${DRAGON_ACCESS_KEY}\", \"dragon_secret_access_key\": \"${DRAGON_SECRET_ACCESS_KEY}\"}" > envs.json
