#!/usr/bin/env ruby

require "json"

raise "Please set $ACCESS_TOKEN for the building" unless ENV["ACCESS_TOKEN"]
raise "Please set $DRAGON_ACCESS_KEY for the building" unless ENV["DRAGON_ACCESS_KEY"]
raise "Please set $DRAGON_SECRET_ACCESS_KEY for the building" unless ENV["DRAGON_SECRET_ACCESS_KEY"]

token_file_path = File.expand_path("../../token.json", __FILE__)

File.write(token_file_path, JSON.dump(
             {
               access_token: ENV["ACCESS_TOKEN"],
               dragon_access_key: ENV["DRAGON_ACCESS_KEY"],
               dragon_secret_access_key: ENV["DRAGON_SECRET_ACCESS_KEY"],
             }
           ))
