#!/usr/bin/env bash

# docker
yum install -y docker
systemctl enable docker
systemctl start docker

# kubernetes
sh -c "cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF"

setenforce 0

yum install -y kubelet kubeadm kubectl

systemctl enable kubelet
systemctl start kubelet

kubeadm init --pod-network-cidr=192.168.0.0/16

echo "注意) kubeadm join --token...のコマンドはバックアップをとってください！"
